#!/bin/bash

set -e

echo "Pushing branch: $BRANCH_NAME"

git push origin "$BRANCH_NAME"

echo "Creating Pull Request"

gh pr create \
  --title "$PR_TITLE" \
  --body "Auto-generated by Copilot AI agent." \
  --base main \
  --head "$BRANCH_NAME"

echo "Pull Request created successfully"